name: Cloud Integration Deploy IFlow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SAP/project-piper-action@master
        with:
          command: integrationArtifactDeploy
          flags: --apiServiceKey ${{ secrets.CPIAPISERVICEKEYCREDENTIALSID }} --integrationFlowId Publish_SAP_SFSF_New_Hire_Event_to_Confluent_Kafka_-_SOL
